### PR TITLE
Change Request: Change the wrapping method in TText

### PR DESCRIPTION
**Pull request by nikiroo**
It will now wrap the lines BEFORE the end of the window and will try to do so at a visually acceptable place if possible, or will add a "-" at the end of the line if not possible (if it is only one word).

It will also remove the now useless HScroll.

### CODE REVIEW

**Comment by klamonte** [comment]
I am adding a Viewport interface soon that will change the visible scrollbar functions, and also create TScrollableWindow (another issue).  After that, this PR might have the functionality already here, we will see.

**Comment by nikiroo** [comment]
The functionality I need is present, thanks.

The justify/centre will be nice in my use case, too.

Just 2 small notes on it, if I can:
- You keep a big blob of text, reconstruct it at each `addLine` operation with a known separator, and split it at each `reflow` with the same separator, then never use the text blob for anything else
  - you may want to keep a list of lines instead, and simply add a line to it on `addLine`
- You can add lines but you cannot clear the content (`TText.clear()` ?) nor change the text (`TText.setText(String text`) ?) -- do you think `TText` could become programmatically modifiable in the future?

**Comment by klamonte** [comment]
Yup, you're right: TText needs getText() and setText() at the very least.  Thanks for catching that.

We will have a number of performance improvement releases after the API is rounded out.  TText will also have a friend later this: TEditor, which will be a full-featured editing component (including syntax highlighting).

**Comment by klamonte** [comment]
TText now has getter/setter for text, and an exposed Scrollable interface.

**Pull request closed without merging**
